name: Build & Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        framework: [net8.0, net10.0]
    name: build (${{ matrix.framework }})
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-dotnet-build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.framework }}
          path: |
            src/**/bin/Release/${{ matrix.framework }}/**
            tests/**/bin/Release/${{ matrix.framework }}/**
            src/**/obj/Release/${{ matrix.framework }}/**
            tests/**/obj/Release/${{ matrix.framework }}/**
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        framework: [net8.0, net10.0]
        project: [Unit, Integration]
    name: test (${{ matrix.framework }}, ${{ matrix.project }})
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-dotnet-build
        with:
          build: false

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.framework }}

      - name: ${{ matrix.project }} Tests
        run: dotnet test tests/CosmosDB.InMemoryEmulator.Tests.${{ matrix.project }} --configuration Release --no-build --verbosity normal --framework ${{ matrix.framework }}
